apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      name: discord-bot
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: marcinator/discord-bot:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      